CATEGORIES = [
    "Carbohidratos",
    "Proteína animal",
    "Proteína vegetal",
    "Fruta y verdura",
    "Grasas saludables",
]

FOODS = [
    {"name": "Arroz integral", "category": "Carbohidratos", "calories": 360, "protein": 7.5, "carbs": 76.0, "fat": 2.7},
    {"name": "Avena", "category": "Carbohidratos", "calories": 389, "protein": 16.9, "carbs": 66.3, "fat": 6.9},
    {"name": "Pan integral", "category": "Carbohidratos", "calories": 247, "protein": 13.0, "carbs": 41.0, "fat": 4.2},
    {"name": "Pasta integral", "category": "Carbohidratos", "calories": 348, "protein": 12.5, "carbs": 70.0, "fat": 2.0},
    {"name": "Quinoa", "category": "Carbohidratos", "calories": 368, "protein": 14.1, "carbs": 64.2, "fat": 6.1},
    {"name": "Batata", "category": "Carbohidratos", "calories": 86, "protein": 1.6, "carbs": 20.1, "fat": 0.1},
    {"name": "Patata cocida", "category": "Carbohidratos", "calories": 87, "protein": 1.9, "carbs": 20.1, "fat": 0.1},
    {"name": "Cuscús", "category": "Carbohidratos", "calories": 376, "protein": 12.8, "carbs": 77.4, "fat": 0.6},
    {"name": "Maíz", "category": "Carbohidratos", "calories": 365, "protein": 9.4, "carbs": 74.3, "fat": 4.7},
    {"name": "Tortilla de maíz", "category": "Carbohidratos", "calories": 218, "protein": 5.7, "carbs": 44.6, "fat": 2.9},
    {"name": "Harina de trigo", "category": "Carbohidratos", "calories": 364, "protein": 10.3, "carbs": 76.3, "fat": 1.0},
    {"name": "Cebada", "category": "Carbohidratos", "calories": 354, "protein": 12.5, "carbs": 73.5, "fat": 2.3},
    {"name": "Mijo", "category": "Carbohidratos", "calories": 378, "protein": 11.0, "carbs": 72.8, "fat": 4.2},
    {"name": "Sémola", "category": "Carbohidratos", "calories": 360, "protein": 12.7, "carbs": 72.8, "fat": 1.1},
    {"name": "Arepa", "category": "Carbohidratos", "calories": 218, "protein": 5.4, "carbs": 44.0, "fat": 2.1},
    {"name": "Tostadas", "category": "Carbohidratos", "calories": 407, "protein": 11.0, "carbs": 74.0, "fat": 9.0},
    {"name": "Arroz basmati", "category": "Carbohidratos", "calories": 351, "protein": 7.0, "carbs": 78.0, "fat": 0.7},
    {"name": "Arroz blanco", "category": "Carbohidratos", "calories": 365, "protein": 7.1, "carbs": 80.0, "fat": 0.7},
    {"name": "Granola", "category": "Carbohidratos", "calories": 471, "protein": 10.0, "carbs": 64.0, "fat": 20.0},
    {"name": "Cereal de maíz", "category": "Carbohidratos", "calories": 357, "protein": 7.3, "carbs": 83.0, "fat": 1.5},
    {"name": "Galletas integrales", "category": "Carbohidratos", "calories": 430, "protein": 8.0, "carbs": 70.0, "fat": 12.0},
    {"name": "Pan pita", "category": "Carbohidratos", "calories": 275, "protein": 9.1, "carbs": 55.7, "fat": 1.2},
    {"name": "Tortitas de arroz", "category": "Carbohidratos", "calories": 387, "protein": 8.0, "carbs": 81.0, "fat": 3.0},
    {"name": "Bagel", "category": "Carbohidratos", "calories": 250, "protein": 10.0, "carbs": 48.0, "fat": 1.5},
    {"name": "Fideos", "category": "Carbohidratos", "calories": 371, "protein": 12.0, "carbs": 72.0, "fat": 2.0},
    {"name": "Ñoquis", "category": "Carbohidratos", "calories": 200, "protein": 4.0, "carbs": 40.0, "fat": 1.0},
    {"name": "Pan de centeno", "category": "Carbohidratos", "calories": 259, "protein": 9.0, "carbs": 48.0, "fat": 3.3},
    {"name": "Castañas cocidas", "category": "Carbohidratos", "calories": 210, "protein": 2.4, "carbs": 45.0, "fat": 2.0},
    {"name": "Plátano macho", "category": "Carbohidratos", "calories": 122, "protein": 1.3, "carbs": 32.0, "fat": 0.4},
    {"name": "Tapioca", "category": "Carbohidratos", "calories": 358, "protein": 0.2, "carbs": 88.7, "fat": 0.0},
    {"name": "Pollo pechuga", "category": "Proteína animal", "calories": 165, "protein": 31.0, "carbs": 0.0, "fat": 3.6},
    {"name": "Pavo pechuga", "category": "Proteína animal", "calories": 135, "protein": 29.0, "carbs": 0.0, "fat": 1.6},
    {"name": "Ternera magra", "category": "Proteína animal", "calories": 217, "protein": 26.1, "carbs": 0.0, "fat": 12.0},
    {"name": "Lomo de cerdo", "category": "Proteína animal", "calories": 196, "protein": 27.0, "carbs": 0.0, "fat": 9.0},
    {"name": "Atún", "category": "Proteína animal", "calories": 132, "protein": 29.0, "carbs": 0.0, "fat": 1.0},
    {"name": "Salmón", "category": "Proteína animal", "calories": 208, "protein": 20.0, "carbs": 0.0, "fat": 13.0},
    {"name": "Merluza", "category": "Proteína animal", "calories": 90, "protein": 19.0, "carbs": 0.0, "fat": 1.0},
    {"name": "Bacalao", "category": "Proteína animal", "calories": 105, "protein": 23.0, "carbs": 0.0, "fat": 1.0},
    {"name": "Sardinas", "category": "Proteína animal", "calories": 208, "protein": 25.0, "carbs": 0.0, "fat": 11.0},
    {"name": "Huevos", "category": "Proteína animal", "calories": 143, "protein": 13.0, "carbs": 1.1, "fat": 9.5},
    {"name": "Claras de huevo", "category": "Proteína animal", "calories": 52, "protein": 11.0, "carbs": 0.7, "fat": 0.2},
    {"name": "Yogur griego", "category": "Proteína animal", "calories": 97, "protein": 9.0, "carbs": 3.6, "fat": 5.0},
    {"name": "Queso fresco", "category": "Proteína animal", "calories": 98, "protein": 11.0, "carbs": 3.0, "fat": 4.0},
    {"name": "Requesón", "category": "Proteína animal", "calories": 98, "protein": 11.1, "carbs": 3.4, "fat": 4.3},
    {"name": "Leche desnatada", "category": "Proteína animal", "calories": 35, "protein": 3.4, "carbs": 5.0, "fat": 0.1},
    {"name": "Jamón cocido", "category": "Proteína animal", "calories": 145, "protein": 21.0, "carbs": 1.5, "fat": 5.0},
    {"name": "Jamón serrano", "category": "Proteína animal", "calories": 241, "protein": 31.0, "carbs": 0.0, "fat": 12.0},
    {"name": "Pechuga de pavo fiambre", "category": "Proteína animal", "calories": 104, "protein": 17.0, "carbs": 2.0, "fat": 2.0},
    {"name": "Gambas", "category": "Proteína animal", "calories": 99, "protein": 24.0, "carbs": 0.2, "fat": 0.3},
    {"name": "Pulpo", "category": "Proteína animal", "calories": 82, "protein": 15.0, "carbs": 2.0, "fat": 1.0},
    {"name": "Calamar", "category": "Proteína animal", "calories": 92, "protein": 16.0, "carbs": 3.0, "fat": 1.4},
    {"name": "Mejillones", "category": "Proteína animal", "calories": 86, "protein": 12.0, "carbs": 3.7, "fat": 2.2},
    {"name": "Trucha", "category": "Proteína animal", "calories": 148, "protein": 20.0, "carbs": 0.0, "fat": 6.5},
    {"name": "Conejo", "category": "Proteína animal", "calories": 173, "protein": 33.0, "carbs": 0.0, "fat": 3.6},
    {"name": "Carne de res magra", "category": "Proteína animal", "calories": 187, "protein": 26.0, "carbs": 0.0, "fat": 8.0},
    {"name": "Solomillo de cerdo", "category": "Proteína animal", "calories": 143, "protein": 26.0, "carbs": 0.0, "fat": 3.5},
    {"name": "Pechuga de pollo asada", "category": "Proteína animal", "calories": 174, "protein": 32.0, "carbs": 0.0, "fat": 3.7},
    {"name": "Queso mozzarella light", "category": "Proteína animal", "calories": 200, "protein": 24.0, "carbs": 2.0, "fat": 10.0},
    {"name": "Sardinas en lata", "category": "Proteína animal", "calories": 208, "protein": 24.6, "carbs": 0.0, "fat": 11.5},
    {"name": "Caballa", "category": "Proteína animal", "calories": 205, "protein": 19.0, "carbs": 0.0, "fat": 14.0},
    {"name": "Tofu firme", "category": "Proteína vegetal", "calories": 144, "protein": 15.7, "carbs": 3.9, "fat": 8.7},
    {"name": "Lentejas", "category": "Proteína vegetal", "calories": 352, "protein": 24.6, "carbs": 63.4, "fat": 1.1},
    {"name": "Garbanzos", "category": "Proteína vegetal", "calories": 364, "protein": 19.3, "carbs": 61.0, "fat": 6.0},
    {"name": "Alubias negras", "category": "Proteína vegetal", "calories": 339, "protein": 21.0, "carbs": 62.0, "fat": 1.4},
    {"name": "Alubias rojas", "category": "Proteína vegetal", "calories": 333, "protein": 23.6, "carbs": 60.0, "fat": 0.8},
    {"name": "Edamame", "category": "Proteína vegetal", "calories": 122, "protein": 11.0, "carbs": 8.9, "fat": 5.2},
    {"name": "Tempeh", "category": "Proteína vegetal", "calories": 193, "protein": 20.0, "carbs": 8.0, "fat": 11.0},
    {"name": "Soja texturizada", "category": "Proteína vegetal", "calories": 332, "protein": 50.0, "carbs": 30.0, "fat": 1.0},
    {"name": "Seitán", "category": "Proteína vegetal", "calories": 370, "protein": 75.0, "carbs": 14.0, "fat": 2.0},
    {"name": "Hummus", "category": "Proteína vegetal", "calories": 166, "protein": 7.9, "carbs": 14.3, "fat": 9.6},
    {"name": "Guisantes", "category": "Proteína vegetal", "calories": 81, "protein": 5.4, "carbs": 14.0, "fat": 0.4},
    {"name": "Habitas", "category": "Proteína vegetal", "calories": 88, "protein": 7.6, "carbs": 16.0, "fat": 0.4},
    {"name": "Lupinos", "category": "Proteína vegetal", "calories": 119, "protein": 15.6, "carbs": 9.9, "fat": 2.9},
    {"name": "Cacahuetes", "category": "Proteína vegetal", "calories": 567, "protein": 25.8, "carbs": 16.1, "fat": 49.2},
    {"name": "Almendras", "category": "Proteína vegetal", "calories": 579, "protein": 21.2, "carbs": 21.6, "fat": 49.9},
    {"name": "Pistachos", "category": "Proteína vegetal", "calories": 562, "protein": 20.2, "carbs": 27.5, "fat": 45.4},
    {"name": "Anacardos", "category": "Proteína vegetal", "calories": 553, "protein": 18.2, "carbs": 30.2, "fat": 43.9},
    {"name": "Semillas de calabaza", "category": "Proteína vegetal", "calories": 559, "protein": 30.2, "carbs": 10.7, "fat": 49.0},
    {"name": "Semillas de chía", "category": "Proteína vegetal", "calories": 486, "protein": 16.5, "carbs": 42.1, "fat": 30.7},
    {"name": "Semillas de lino", "category": "Proteína vegetal", "calories": 534, "protein": 18.3, "carbs": 28.9, "fat": 42.2},
    {"name": "Quinoa cocida", "category": "Proteína vegetal", "calories": 120, "protein": 4.4, "carbs": 21.3, "fat": 1.9},
    {"name": "Lentejas cocidas", "category": "Proteína vegetal", "calories": 116, "protein": 9.0, "carbs": 20.1, "fat": 0.4},
    {"name": "Garbanzos cocidos", "category": "Proteína vegetal", "calories": 164, "protein": 8.9, "carbs": 27.4, "fat": 2.6},
    {"name": "Tofu ahumado", "category": "Proteína vegetal", "calories": 150, "protein": 16.0, "carbs": 2.0, "fat": 9.0},
    {"name": "Proteína vegetal en polvo", "category": "Proteína vegetal", "calories": 380, "protein": 75.0, "carbs": 8.0, "fat": 6.0},
    {"name": "Azukis", "category": "Proteína vegetal", "calories": 329, "protein": 20.0, "carbs": 62.0, "fat": 0.5},
    {"name": "Soja cocida", "category": "Proteína vegetal", "calories": 173, "protein": 16.6, "carbs": 9.9, "fat": 9.0},
    {"name": "Alubias blancas", "category": "Proteína vegetal", "calories": 336, "protein": 21.4, "carbs": 60.3, "fat": 1.0},
    {"name": "Alubias pintas", "category": "Proteína vegetal", "calories": 347, "protein": 21.0, "carbs": 63.0, "fat": 1.2},
    {"name": "Judías mungo", "category": "Proteína vegetal", "calories": 347, "protein": 24.0, "carbs": 63.0, "fat": 1.2},
    {"name": "Manzana", "category": "Fruta y verdura", "calories": 52, "protein": 0.3, "carbs": 13.8, "fat": 0.2},
    {"name": "Plátano", "category": "Fruta y verdura", "calories": 89, "protein": 1.1, "carbs": 22.8, "fat": 0.3},
    {"name": "Naranja", "category": "Fruta y verdura", "calories": 47, "protein": 0.9, "carbs": 11.8, "fat": 0.1},
    {"name": "Pera", "category": "Fruta y verdura", "calories": 57, "protein": 0.4, "carbs": 15.2, "fat": 0.1},
    {"name": "Fresas", "category": "Fruta y verdura", "calories": 32, "protein": 0.7, "carbs": 7.7, "fat": 0.3},
    {"name": "Arándanos", "category": "Fruta y verdura", "calories": 57, "protein": 0.7, "carbs": 14.5, "fat": 0.3},
    {"name": "Kiwi", "category": "Fruta y verdura", "calories": 61, "protein": 1.1, "carbs": 14.7, "fat": 0.5},
    {"name": "Piña", "category": "Fruta y verdura", "calories": 50, "protein": 0.5, "carbs": 13.1, "fat": 0.1},
    {"name": "Mango", "category": "Fruta y verdura", "calories": 60, "protein": 0.8, "carbs": 15.0, "fat": 0.4},
    {"name": "Papaya", "category": "Fruta y verdura", "calories": 43, "protein": 0.5, "carbs": 10.8, "fat": 0.3},
    {"name": "Sandía", "category": "Fruta y verdura", "calories": 30, "protein": 0.6, "carbs": 7.6, "fat": 0.2},
    {"name": "Melón", "category": "Fruta y verdura", "calories": 34, "protein": 0.8, "carbs": 8.2, "fat": 0.2},
    {"name": "Uvas", "category": "Fruta y verdura", "calories": 69, "protein": 0.7, "carbs": 18.1, "fat": 0.2},
    {"name": "Cerezas", "category": "Fruta y verdura", "calories": 50, "protein": 1.0, "carbs": 12.2, "fat": 0.3},
    {"name": "Brócoli", "category": "Fruta y verdura", "calories": 34, "protein": 2.8, "carbs": 6.6, "fat": 0.4},
    {"name": "Espinacas", "category": "Fruta y verdura", "calories": 23, "protein": 2.9, "carbs": 3.6, "fat": 0.4},
    {"name": "Lechuga", "category": "Fruta y verdura", "calories": 15, "protein": 1.4, "carbs": 2.9, "fat": 0.2},
    {"name": "Tomate", "category": "Fruta y verdura", "calories": 18, "protein": 0.9, "carbs": 3.9, "fat": 0.2},
    {"name": "Pepino", "category": "Fruta y verdura", "calories": 15, "protein": 0.7, "carbs": 3.6, "fat": 0.1},
    {"name": "Zanahoria", "category": "Fruta y verdura", "calories": 41, "protein": 0.9, "carbs": 9.6, "fat": 0.2},
    {"name": "Pimiento rojo", "category": "Fruta y verdura", "calories": 31, "protein": 1.0, "carbs": 6.0, "fat": 0.3},
    {"name": "Pimiento verde", "category": "Fruta y verdura", "calories": 20, "protein": 0.9, "carbs": 4.6, "fat": 0.2},
    {"name": "Calabacín", "category": "Fruta y verdura", "calories": 17, "protein": 1.2, "carbs": 3.1, "fat": 0.3},
    {"name": "Berenjena", "category": "Fruta y verdura", "calories": 25, "protein": 1.0, "carbs": 6.0, "fat": 0.2},
    {"name": "Coliflor", "category": "Fruta y verdura", "calories": 25, "protein": 1.9, "carbs": 5.0, "fat": 0.3},
    {"name": "Champiñones", "category": "Fruta y verdura", "calories": 22, "protein": 3.1, "carbs": 3.3, "fat": 0.3},
    {"name": "Cebolla", "category": "Fruta y verdura", "calories": 40, "protein": 1.1, "carbs": 9.3, "fat": 0.1},
    {"name": "Acelga", "category": "Fruta y verdura", "calories": 19, "protein": 1.8, "carbs": 3.7, "fat": 0.2},
    {"name": "Calabaza", "category": "Fruta y verdura", "calories": 26, "protein": 1.0, "carbs": 6.5, "fat": 0.1},
    {"name": "Remolacha", "category": "Fruta y verdura", "calories": 43, "protein": 1.6, "carbs": 10.0, "fat": 0.2},
    {"name": "Aguacate", "category": "Grasas saludables", "calories": 160, "protein": 2.0, "carbs": 8.5, "fat": 14.7},
    {"name": "Aceite de oliva", "category": "Grasas saludables", "calories": 884, "protein": 0.0, "carbs": 0.0, "fat": 100.0},
    {"name": "Aceite de coco", "category": "Grasas saludables", "calories": 892, "protein": 0.0, "carbs": 0.0, "fat": 100.0},
    {"name": "Aceite de aguacate", "category": "Grasas saludables", "calories": 884, "protein": 0.0, "carbs": 0.0, "fat": 100.0},
    {"name": "Nueces", "category": "Grasas saludables", "calories": 654, "protein": 15.2, "carbs": 13.7, "fat": 65.2},
    {"name": "Almendras", "category": "Grasas saludables", "calories": 579, "protein": 21.2, "carbs": 21.6, "fat": 49.9},
    {"name": "Avellanas", "category": "Grasas saludables", "calories": 628, "protein": 15.0, "carbs": 16.7, "fat": 60.8},
    {"name": "Pistachos", "category": "Grasas saludables", "calories": 562, "protein": 20.2, "carbs": 27.5, "fat": 45.4},
    {"name": "Anacardos", "category": "Grasas saludables", "calories": 553, "protein": 18.2, "carbs": 30.2, "fat": 43.9},
    {"name": "Mantequilla de cacahuete", "category": "Grasas saludables", "calories": 588, "protein": 25.0, "carbs": 20.0, "fat": 50.0},
    {"name": "Tahini", "category": "Grasas saludables", "calories": 595, "protein": 17.0, "carbs": 21.0, "fat": 53.0},
    {"name": "Semillas de chía", "category": "Grasas saludables", "calories": 486, "protein": 16.5, "carbs": 42.1, "fat": 30.7},
    {"name": "Semillas de lino", "category": "Grasas saludables", "calories": 534, "protein": 18.3, "carbs": 28.9, "fat": 42.2},
    {"name": "Semillas de calabaza", "category": "Grasas saludables", "calories": 559, "protein": 30.2, "carbs": 10.7, "fat": 49.0},
    {"name": "Semillas de sésamo", "category": "Grasas saludables", "calories": 573, "protein": 17.7, "carbs": 23.5, "fat": 49.7},
    {"name": "Aceitunas", "category": "Grasas saludables", "calories": 115, "protein": 0.8, "carbs": 6.3, "fat": 10.7},
    {"name": "Queso curado", "category": "Grasas saludables", "calories": 402, "protein": 25.0, "carbs": 1.3, "fat": 33.0},
    {"name": "Salmón ahumado", "category": "Grasas saludables", "calories": 117, "protein": 18.0, "carbs": 0.0, "fat": 4.0},
    {"name": "Yema de huevo", "category": "Grasas saludables", "calories": 322, "protein": 16.0, "carbs": 3.6, "fat": 27.0},
    {"name": "Chocolate negro 85%", "category": "Grasas saludables", "calories": 600, "protein": 7.8, "carbs": 19.0, "fat": 50.0},
    {"name": "Coco rallado", "category": "Grasas saludables", "calories": 660, "protein": 6.9, "carbs": 24.0, "fat": 65.0},
    {"name": "Mantequilla de almendra", "category": "Grasas saludables", "calories": 614, "protein": 21.0, "carbs": 19.0, "fat": 56.0},
    {"name": "Mayonesa casera", "category": "Grasas saludables", "calories": 680, "protein": 1.0, "carbs": 1.0, "fat": 75.0},
    {"name": "Aceite de sésamo", "category": "Grasas saludables", "calories": 884, "protein": 0.0, "carbs": 0.0, "fat": 100.0},
    {"name": "Aceite de girasol", "category": "Grasas saludables", "calories": 884, "protein": 0.0, "carbs": 0.0, "fat": 100.0},
    {"name": "Aceite de canola", "category": "Grasas saludables", "calories": 884, "protein": 0.0, "carbs": 0.0, "fat": 100.0},
    {"name": "Mantequilla", "category": "Grasas saludables", "calories": 717, "protein": 0.9, "carbs": 0.1, "fat": 81.0},
    {"name": "Nueces de macadamia", "category": "Grasas saludables", "calories": 718, "protein": 7.9, "carbs": 13.8, "fat": 75.8},
    {"name": "Pecanas", "category": "Grasas saludables", "calories": 691, "protein": 9.2, "carbs": 13.9, "fat": 72.0},
    {"name": "Semillas de girasol", "category": "Grasas saludables", "calories": 584, "protein": 20.8, "carbs": 20.0, "fat": 51.5},
    {"name": "Crema de cacahuete light", "category": "Grasas saludables", "calories": 520, "protein": 24.0, "carbs": 24.0, "fat": 40.0},
    {"name": "Anchoas", "category": "Grasas saludables", "calories": 210, "protein": 29.0, "carbs": 0.0, "fat": 10.0},
    {"name": "Sardinas en aceite", "category": "Grasas saludables", "calories": 208, "protein": 24.6, "carbs": 0.0, "fat": 11.5},
]
